services:
  bitchx:
    build:
      context: .
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    image: bitchx:local
    container_name: bitchx_session
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
    user: "${UID}:${GID}"
    volumes:
      - ./config:/home/you/.BitchX
      - ./osiris-config:/home/you/osiris
      - ./config/.ircrc:/home/you/.ircrc
      - ./launch-bx.sh:/home/you/launch-bx.sh
